version: 2.0
jobs:

  unittests:
    working_directory: ~/repo
    docker:
      - image: python:3.7
    steps:
      - checkout
      - run:
          name: Install test dependencies
          command:  pip install -r requirement.txt
      - run:
          name: Run unit tests
          command: pytest test/*.py


workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unittests:
          filters:
            branches:
              ignore:
                - master
